### ISSUE TITLE
Loading Chinese Characters

### ISSUE THREAD

**Issue by smallshen** [heroslender/menu-framework#6]
It looks like doesn't support Chinese characters

**Comment by heroslender** [comment]
That is because I have a [preset list of characters](https://github.com/heroslender/menu-framework/blob/4e108efb9f909e473ba53c3a5059ef056279a728/core/src/main/kotlin/com/heroslender/hmf/core/font/FontParser.kt#L14) to load from a font. 

What i could do is to allow the user to pass a custom list of characters when calling [`FontParser#getFontFromResources`](https://github.com/heroslender/menu-framework/blob/4e108efb9f909e473ba53c3a5059ef056279a728/core/src/main/kotlin/com/heroslender/hmf/core/font/FontParser.kt#L17). That way, they'll have control over what character get loaded in a font.

**Comment by smallshen** [comment]
It should be fixed by using char range instead of the char string

**Comment by smallshen** [comment]
closed
https://github.com/heroslender/menu-framework/pull/9
